config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  devise_for :users, controllers: { registrations: "registrations" }
  
  namespace :admin do
    resources :dashboards, only: [:index]
    resources :users
    resources :companies 
    resources :positions, only: [:index]
    
    root to: "dashboards#index"
  end
  
  
  resources :companies, only: [:new, :edit, :create, :update]
  resources :positions do 
    resources :applicants, only: [:index]
    put :update_applicants_status, on: :member
  end

  resources :applicants, only: [:new, :create]
    resources :applied_vacancies, only: [:index]

  root "home#index"
  get "/vaga/:slug", action: :public_position, controller: :positions, as: :public_position
  # dashboard para a empresa
  get "/dashboard", action: :dashboard, controller: :companies, as: :company_dashboard
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :company
  enum career: [:general_practitioners, :surgery, :orthopedics, :dermatology, :cardiology, 
    :ophthalmology, :nutrition, :other]
  enum contract: [:clt, :pj, :match]
  has_rich_text :description
  validates :name, :career, :contract, :city, :state, :summary, presence: true
  before_save :set_slug
    
  has_many :applicants
  
  private
    
  def self.ransackable_attributes(auth_object = nil)
    ["name", "career", "city", "company_id", "contract", "created_at", "id", "publish", "remote", "slug", "state", "summary", "updated_at"]
  end

  def set_slug
    self.slug = "#{self.company.name.parameterize}-#{self.name.parameterize}"
  end
end

app/controllers/admin/positions_controller.rb
module Admin
  class PositionsController < BaseController
    before_action :authenticate_user!

    def index
      @q = Position.ransack(params[:q]) # Use Position instead of Company
      if params[:company_id].present?
        @company = Company.find(params[:company_id])
        @positions = @company.positions
        @q.result = @positions # Apply company filter to the search
      else
        @positions = @q.result(distinct: true)
      end
      @pagy, @positions = pagy(@positions)
      @companies = Company.all.order(:name)
    end
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_company, :set_I18n_careers, :set_I18n_contracts, except: [:public_position]
  before_action :set_position, only: [:edit, :show, :update, :destroy]

  def index
    @positions = @company.positions
    @pagy, @positions = pagy(@positions)
  end

  def show
    render :form
  end

  def new
    @position = @company.positions.new
    render :form
  end

  def create
    @position = @company.positions.new(params_position)
    if @position.save
      flash[:success] = "Vaga cadastrada com sucesso!"
      redirect_to positions_path
    else
      render :form, status: :unprocessable_entity
    end
  end

  def edit
    render :form
  end

  def update
    if @position.update(params_position)
      flash[:notice] = "Vaga atualizada com sucesso!"
      redirect_to positions_path
    else
      render :form, status: :unprocessable_entity
    end
  end

  def destroy
    if @position.destroy
      flash[:notice] = "Vaga excluída com sucesso!"
    else
      flash[:alert] = "Erro ao excluir vaga!"
    end
    redirect_to positions_path
  end

  def public_position
    @position = Position.find_by(slug: params[:slug])
    if user_signed_in?
      @applicant = current_user.applicants.new(position_id: @position.id)
      @user_applicants = UserApplicantService.new(current_user.id, @position.id).call
    end
  end

  def update_applicants_status
    @position = Position.find(params[:id])
    applicants_ids = params[:position][:applicants_status].split(",").reject(&:blank?)
    UpdateVacancyStatusService.new(@position).call
    flash[:notice] = "Status dos candidatos atualizado com sucesso!"
    redirect_to positions_path
  end  
  
  private
    def set_company
      redirect_to new_company_path if current_user.company.nil?
      @company = current_user.company
    end

    def set_position
      @position = @company.positions.find(params[:id])
    end

    def set_I18n_careers
      @careers = I18n.t('activerecord.attributes.position.careers')
    end

    def set_I18n_contracts
      @contracts = I18n.t('activerecord.attributes.position.contracts')
    end

    def params_position
      params.require(:position).permit(:name, :career, :contract, :remote, :city, :state, :summary, :description, :publish)
    end
end

app/helpers/positions_helper.rb
module PositionsHelper
  def text_position(position)
    "A empresa #{position.company.name} em #{position.city} está com a vaga de #{position.name}.Veja mais detalhes no nosso mural! #{url_position(position)}"
  end

  def url_position(position)
    public_position_url(position.slug)
  end

  def formatted_career_and_contract(position)
    career_translation = I18n.t('activerecord.attributes.position.careers')[position.career.to_sym]
    contract_translation = I18n.t('activerecord.attributes.position.contracts')[position.contract.to_sym]

    "#{career_translation} - #{position.city} - #{contract_translation}"
  end

  def career_name(career)
    I18n.t("activerecord.attributes.position.careers")[career.to_sym]
  end

  def contract_name(contract)
    I18n.t("activerecord.attributes.position.contracts")[contract.to_sym]
  end

  def modality(position)
    position.remote? ? 'Remoto' : 'Presencial'
  end
end

app/views/positions/_position.html.erb
<div class="flex items-center justify-center mt-8">
  <div class="relative flex w-11/12 h-64 flex-row rounded-xl bg-white bg-clip-border text-gray-700 shadow-md">
    <div class="relative m-0 shrink-0 overflow-hidden rounded-xl rounded-r-none bg-white bg-clip-border text-gray-700">
      <%= image_tag position.company.logo, alt: "Logo da marca #{position.company.name}", class: 'h-64 w-96 object-cover' %>
    </div>
      <div class="p-6">
        <h6 class="mb-4 block font-sans text-base font-semibold uppercase leading-relaxed tracking-normal text-pink-500 antialiased">
          <%= position.name %>
        </h6>
        <h4 class="mb-4 block font-sans text-2xl font-semibold leading-snug tracking-normal text-blue-gray-900 antialiased">
          <%= formatted_career_and_contract(position) %>
        </h4>
        <p class="mb-4 block font-sans text-base font-normal leading-relaxed text-gray-700 antialiased">
            A <%= position.name %> está em busca de um(a) veterinário(a) com especialidade em <%= "#{I18n.t('activerecord.attributes.position.careers')[position.career.to_sym]}" %> para atuar em sua unidade no <%= position.city %>.
        </p>
        <div class="flex justify-between items-center">
            <%= link_to "Ver mais", public_position_path(position.slug), class: 'flex select-none items-center gap-2 middle none center mr-4 rounded-lg bg-red-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-red-500/20 transition-all hover:shadow-lg hover:shadow-red-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none' %>
            <% if user_signed_in? %>   
              <% if !UserApplicantService.new(current_user.id, position.id).call %>
                <div class="flex justify-center items-center"> 
                  <%=  link_to "Candidatar-se",
                  new_applicant_path(position_id: position.id),
                  remote: true,
                  class: 'flex select-none items-center gap-2 middle none center mr-4 rounded-lg bg-blue-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-blue-500/20 transition-all hover:shadow-lg hover:shadow-blue-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none'
                  %>
                </div>
                <%#= link_to "Candidatar-se", public_position_path(position.slug), class: 'flex select-none items-center gap-2 middle none center mr-4 rounded-lg bg-blue-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-blue-500/20 transition-all hover:shadow-lg hover:shadow-blue-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none' %>
              <% end %>
            <% end %>
          <div class="flex justify-center items-center gap-5">
            <%= render partial: 'shared/social_network', locals: { position: position } %>
          </div>
        </div> 
      </div>
    </div>
</div>

app/views/positions/form.html.erb
<section class="py-8 bg-[#f5f5f5]">
  <div class="container px-10 mx-auto flex justify-center">
    <div class="pb-16 pt-12 border border-dark-blue rounded-3xl w-10/12">
      <p class="text-3xl font-heading font-sourcesans font-medium pl-16">
        <% if action_name == 'show' %>
          <p class="text-center text-3xl font-heading font-sourcesans font-medium"> <%= @position.name %> </p>
        <% elsif action_name == 'edit' %>
          <p class="text-center text-3xl font-heading font-sourcesans font-medium"> Editar vaga </p>
        <% else %>
          <p class="text-center text-3xl font-heading font-sourcesans font-medium"> Publicar vaga </p>
        <% end %>
        </p>
        <div class="flex flex-wrap px-9 mb-8 md:mb-0 justify-center">
          <div class="mt-5 md:col-span-2 md:mt-0">
            <%= simple_form_for [@position], defaults: { disabled: action_name == 'show' }, remote: true do |f| %>
              <%= f.error_notification %>
              <div class="overflow-hidden">
                <div class="px-4 py-5 sm:p-6">
                  <div class="grid grid-cols-6 gap-6">
                    <div class="col-span-6">
                      <%= f.input :name,
                              placeholder: "Nome",
                              class: "block shadow appearance-none border border-gray-300 rounded w-full py-2 px-3 bg-white focus:outline-none focus:ring-0 focus:border-blue-500 text-gray-400 leading-6 transition-colors duration-200 ease-in-out string optional"
                          %>
                    </div>
                    <div class="col-span-6 sm:col-span-3">
                      <%= f.input :career,
                              as: :select,
                              collection: @careers,
                              label_method: :second,
                              value_method: :first,
                              include_blank: false,
                              selected: @position.career,
                              class: "w-100 shadow appearance-none border border-gray-300 rounded w-full py-2 px-3 bg-white focus:outline-none focus:ring-0 focus:border-blue-500 text-gray-400 leading-6 transition-colors duration-200 ease-in-out string optional"
                          %>
                    </div>
                    <div class="col-span-6 sm:col-span-3">
                      <%= f.input :contract,
                                  as: :select,
                                  collection: @contracts,
                                  label_method: :second,
                                  value_method: :first,
                                  include_blank: false,
                                  selected: @position.contract,
                                  class: "w-100 shadow appearance-none border border-gray-300 rounded w-full py-2 px-3 bg-white focus:outline-none focus:ring-0 focus:border-blue-500 text-gray-400 leading-6 transition-colors duration-200 ease-in-out string optional"
                          %>
                    </div>
                    <div class="col-span-6 sm:col-span-3">
                      <%= f.input :remote %>
                    </div>
                    <div class="col-span-6 sm:col-span-3">
                      <%= f.input :publish %>
                    </div>
                    <div class="col-span-6 sm:col-span-3">
                      <%= f.input :city,
                              placeholder: "Cidade",
                              class: "shadow appearance-none border border-gray-300 rounded-md w-full py-2 px-3 bg-white focus:outline-none focus:ring-0 focus:border-blue-500 text-gray-400 leading-6 transition-colors duration-200 ease-in-out string optional"
                          %>
                    </div>
                    <div class="col-span-6 sm:col-span-3 mt-2">
                      <%= f.input :state,
                            as: :select,
                            collection: Brazil.states,
                            label_method: :second,
                            value_method: :first,
                            placeholder: "Estado",
                            class: "shadow appearance-none border border-gray-300 rounded-md w-full py-2 px-3 bg-white focus:outline-none focus:ring-0 focus:border-blue-500 text-gray-400 leading-6 transition-colors duration-200 ease-in-out string optional"
                      %>
                    </div>
                    <div class="col-span-6 flex items-center"> 
                      <div data-controller="summary" 
                      class="flex-1 relative rounded-md shadow-sm">
                        <%= f.input :summary,
                              placeholder: "Resumo da vaga",
                              maxlength: 360,
                              input_html: { class: "count-textarea", rows: 4 },
                              class: "form-input py-2 px-3 block w-full leading-5 rounded-md transition duration-150 ease-in-out sm:text-sm sm:leading-5"
                        %>
                        <div id="the-count" class="absolute inset-y-5 right-0 pr-3 flex items-center pointer-events-none">
                          <span id="current" class="text-gray-500 text-sm">0</span>
                          <span id="maximum" class="text-gray-500 text-sm">/ 360</span>
                        </div>
                      </div>
                    </div>
                    <div class="col-span-6">
                      <%=f.label :description, "Descrição", class: "block text-sm font-medium text-gray-600" %>
                      <%= f.rich_text_area :description,
                            placeholder: "Descrição da vaga",
                            class: "shadow appearance-none border border-gray-300 py-2 px-3 bg-white focus:outline-none focus:ring-0 focus:border-blue-500 text-gray-400 leading-6 transition-colors duration-200 ease-in-out string optional"
                      %>
                    </div>
                    
                      <% if action_name == 'show' %>
                        <%= link_to "EDITAR", edit_position_path(@position), class: "middle none center rounded-lg bg-orange-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-orange-500/20 transition-all hover:shadow-lg hover:shadow-orange-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" %>
                      <% else %>
                        <%= f.submit "SALVAR", class:"middle none center mr-4 rounded-lg bg-green-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-green-500/20 transition-all hover:shadow-lg hover:shadow-green-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" %>
                      <% end %>
                      <%= link_to "VOLTAR", positions_path(@position), class: "middle none center mr-4 rounded-lg bg-blue-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-blue-500/20 transition-all hover:shadow-lg hover:shadow-blue-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/positions/index.html.erb
<section class="py-8 bg-blueGray-50">
  <div class="container px-4 mx-auto flex justify-center">
    <div class="p-7 pb-16 pt-12 border border-dark-blue rounded-3xl w-11/12">
      <div class="flex flex-wrap px-9 md:mb-0">
        <div class="w-full md:w-1/2">
          <h3 class="text-3xl font-heading font-sourcesans font-medium text-gray-700">
            Minhas Vagas
          </h3>
        </div>
        <div class="w-full md:w-1/2 max-w-max md:ml-auto">
          <%= link_to "Cadastrar Nova vaga", new_position_path, class: "middle none center mr-4 rounded-lg bg-blue-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-blue-500/20 transition-all hover:shadow-lg hover:shadow-blue-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" %>
        </div>
      </div>
      <div class="overflow-x-auto my-10">
        <div class="inline-block min-w-full overflow-hidden ">
          <table class="table table-zebra w-full my-4">
            <thead>
              <tr>
                <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                  <%= t('activerecord.attributes.position.name') %>
                </th>
                <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                  <%= t('activerecord.attributes.position.career') %>
                </th>
                <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                  <%= t('activerecord.attributes.position.city') %>
                </th>
                <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                  <%= t('activerecord.attributes.position.contract') %>
                </th>
                <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                  <%= t('activerecord.attributes.position.publish') %>
                </th>
                <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                  Candidaturas
                </th>
                <% if current_user.role.eql?("admin") || current_user.role.eql?("company") %>
                  <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                    Ações
                  </th>
                <% end %>
              </tr>
            </thead>

            <tbody>
              <% @positions.each do |position| %>
                <tr>
                  <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 text-left text-blueGray-700">
                    <%= position.name %>
                  </td>
                  <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
                    <%= career_name(position.career) %>
                  </td>
                  <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
                    <%= position.city %>, <%= position.state %>
                  </td>
                  <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
                    <%= contract_name(position.contract) %>
                  </td>
                  <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
                    <%= position.publish ? t('sim') : t('não') %>
                  </td>
                  <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
                    <% if position.applicants.present? %>
                      <%= link_to "Candidaturas (#{position.applicants.count})", position_applicants_path(position), class: "middle none center rounded-lg bg-blue-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-blue-500/20 transition-all hover:shadow-lg hover:shadow-blue-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" %>
                    <% end %>
                  </td>
                  <% if current_user.role.eql?("admin") || current_user.role.eql?("company") %>
                    <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
                      <div class="flex gap-4">
                        <%= link_to edit_position_path(position), class: "middle none center rounded-lg bg-yellow-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-yellow-500/20 transition-all hover:shadow-lg hover:shadow-yellow-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" do %>
                          Editar
                        <% end %> 
                        <%= link_to position_path(position), class:"middle none center rounded-lg bg-green-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-green-500/20 transition-all hover:shadow-lg hover:shadow-green-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" do %>
                          Visualizar
                        <% end %>
                        <%= button_to position_path(position), method: :delete, form: { data: { turbo_confirm: "Você tem certeza?"}}, class:"middle none center rounded-lg bg-red-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-red-500/20 transition-all hover:shadow-lg hover:shadow-red-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" do %>
                          Excluir
                        <% end %>
                        <% if position.applicants.present? %>
                          <%= simple_form_for position, url: update_applicants_status_position_path(position), method: :put, remote: true do |f| %>
                            <%= f.hidden_field :status, value: 'approved' %>
                            <%= f.hidden_field :applicants_status, value: position.applicants.pluck(:id) %>
                            <%= f.submit "Atualizar Status", class:"middle none center rounded-lg bg-blue-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-blue-500/20 transition-all hover:shadow-lg hover:shadow-blue-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" %>
                          <% end %>
                        <% end %>
                      </div>
                    </td>
                  <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%== pagy_nav(@pagy) %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/positions/public_position.html.erb
<section class="py-8 bg-[#f5f5f5]">
  <div class="container px-10 mx-auto flex justify-center">
    <div class="pb-16 pt-12 border border-dark-blue rounded-5xl w-10/12">
      <p class="text-3xl font-heading font-sourcesans font-medium pl-16 text-center mb-4">
        <%= "#{@position.name} - #{@position.company.name}" %>
      </p>
      <p class="text-2xl font-heading font-sourcesans font-medium pl-16 text-center mb-4">
        <%= "#{career_name(@position.career)} - #{@position.city} / #{modality(@position)}, #{@position.state} - #{contract_name(@position.contract)}" %>
      </p>
      <div class="flex flex-wrap px-9 mb-8 md:mb-0 justify-center text-justify">
        <div class="ml-5">
          <%= @position.description %>
        </div>
      </div>
      <div class="p-6">
        <h4 class="mb-4 block text-center font-sans text-2xl font-semibold leading-snug tracking-normal text-blue-gray-900 antialiased">
          Compartilhar
        </h4>
        <div class="flex justify-center items-center gap-5">
          <%= render partial: 'shared/social_network', locals: { position: @position } %>
        </div>
          <% if user_signed_in? %>
            <% if @user_applicants %>
              <p class="text-center mt-8">
                Você já se candidatou a essa vaga.
              </p>
            <% else %>
              <p class="text-center mt-8">
                Insira suas informações para se candidatar a essa vaga <%= @position.name %>.
              </p>
              <%= render partial: 'applicants/form', locals: { applicant: @applicant } %>
            <% end %>
          <% else %>
            <p class="text-center mt-8">
              Você precisa estar logado para se candidatar a essa vaga.
            </p>
          <% end %>
      </div>
    </div>
  </div>
</section>