config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  devise_for :users, controllers: { registrations: "registrations" }
  
  namespace :admin do
    resources :dashboards, only: [:index]
    resources :users
    resources :companies 
    resources :positions, only: [:index]
    
    root to: "dashboards#index"
  end
  
  
  resources :companies, only: [:new, :edit, :create, :update]
  resources :positions do 
    resources :applicants, only: [:index]
    put :update_applicants_status, on: :member
  end

  resources :applicants, only: [:new, :create]
    resources :applied_vacancies, only: [:index]

  root "home#index"
  get "/vaga/:slug", action: :public_position, controller: :positions, as: :public_position
  # dashboard para a empresa
  get "/dashboard", action: :dashboard, controller: :companies, as: :company_dashboard
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :positions
  has_one_attached :logo

  validates :name, :url, :logo, presence: true

  def self.ransackable_associations(auth_object = nil)
    ["logo_attachment", "logo_blob", "positions", "user"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "name", "updated_at", "url", "user_id"]
  end
end

app/controllers/admin/companies_controller.rb
module Admin
  class CompaniesController < BaseController
    before_action :set_company, only: [:edit, :update, :destroy, :show]

    def index
      @q = Company.ransack(params[:q])
      @companies = @q.result(distinct: true).order(:name)
      @pagy, @companies = pagy(@companies)
    end

    def show
      render :form
    end

    def new
      @company = Company.new
      render :form
    end

    def create
      @company = current_user.build_company(company_params)
      if @company.save
        flash[:success] = "Empresa criada com sucesso!"
        redirect_to action: :index
      else
        render :form, status: :unprocessable_entity
      end
    end

    def edit
      render :form
    end

    def update
      if @company.update(companies_params)
        flash[:notice] = "Empresa atualizada com sucesso!"
        redirect_to action: :index
      else
        render :form, status: :unprocessable_entity
      end
    end

    def destroy
      @company.destroy
      redirect_to action: :index
    end

    private

    def set_company
      @company = Company.find(params[:id])
    end

    def company_params
      params.require(:company).permit(
        :name,
        :logo,
        :url,
      )
    end
  end
end
  

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!

  def new
    @company = current_user.build_company
  end

  def edit
    @company = current_user.company
  end

  def create
    @company = current_user.build_company(company_params)
    if @company.save
      flash[:notice] = "Empresa cadastrada com sucesso."
      redirect_to root_path
    else
      flash[:error] = "Erro ao cadastrar empresa."
      render :new, status: :unprocessable_entity
    end
  end
  
  def update
    @company = current_user.company
    if @company.update(company_params)
      flash[:notice] = "Empresa atualizada com sucesso."
      redirect_to root_path
    else
      flash[:error] = "Erro ao atualizar empresa."
      render :edit, status: :unprocessable_entity
    end
  end

  def dashboard
    authorize :company, :dashboard?
    @company = current_user.company
    @positions = @company.positions
    @positions_without_applicants = @positions.select { |position| position.applicants.empty? }
    @positions_with_applicants = @positions.select { |position| position.applicants.any? }
    @applicants = @positions_with_applicants.map { |position| position.applicants }.flatten 
  end

  private
  def company_params
    params.require(:company).permit(:name, :url, :logo)
  end

  def user_not_authorized
    flash[:alert] = "Você não está autorizado a performar essa ação."
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
  def dynamic_url_company
    if current_user.role == "company" && current_user.company.present? && current_user.company.try(:id).present?
      edit_company_path(current_user.company)
    else
      new_company_path
    end
  end
end

app/views/admin/companies/form.html.erb
<section class="py-8 bg-[#f5f5f5] h-full">
  <div class="container px-10 mx-auto flex justify-center">
    <div class="pb-16 pt-12 border border-dark-blue rounded-3xl w-10/12">
      <p class="text-3xl font-heading font-sourcesans font-medium pl-16">
        <% if action_name == 'show' %>
          <p class="pl-16 text-3xl font-heading font-sourcesans font-medium"> Visualizar Empresa </p>
        <% elsif action_name == 'edit' %>
          <p class="pl-16 text-3xl font-heading font-sourcesans font-medium"> Editar Empresa </p>
        <% else %>
          <p class="pl-16 text-3xl font-heading font-sourcesans font-medium"> Cadastrar Empresa </p>
        <% end %>
      </p>
        <div class="flex flex-wrap px-9 mb-8 md:mb-0 justify-center">
          <div class="mt-5 md:col-span-2 md:mt-0" data-controller="visibility">
            <%= simple_form_for [:admin, @company], defaults: { disabled: action_name == "show" } do |f| %>
              <%= f.error_notification %>
              <div class="overflow-hidden">
                <div class="px-4 py-5 sm:p-6">
                  <div class="grid grid-cols-6 gap-6">
                    <div class="col-span-6">
                      <%= f.input :name,
                              placeholder: "Nome",
                              class: "block shadow appearance-none border border-gray-300 rounded w-full py-2 px-3 bg-white focus:outline-none focus:ring-0 focus:border-blue-500 text-gray-400 leading-6 transition-colors duration-200 ease-in-out string optional"
                          %>
                    </div>

                    <div class="col-span-6">
                      <%= f.input :url,
                              placeholder: "URL",
                              class: "block shadow appearance-none border border-gray-300 rounded w-full py-2 px-3 bg-white focus:outline-none focus:ring-0 focus:border-blue-500 text-gray-400 leading-6 transition-colors duration-200 ease-in-out string optional"
                          %>
                    </div>
                    <div class="col-span-6 sm:col-span-3">
                      <%= f.input :logo,
                              placeholder: "Logo",
                              class: "block shadow appearance-none border border-gray-300 rounded w-full py-2 px-3 bg-white focus:outline-none focus:ring-0 focus:border-blue-500 text-gray-400 leading-6 transition-colors duration-200 ease-in-out string optional"
                          %>
                    </div>
                    <div class="col-span-6 sm:col-span-3">
                      <%= image_tag(@company.logo, class: "w-28") if @company.logo.attached? %>
                    </div>
                      <% if action_name == 'show' %>
                        <%= link_to "EDITAR", edit_admin_company_path(@company), class: "middle none center rounded-lg bg-orange-500 py-3 px-8 font-sans text-xs font-bold uppercase text-white shadow-md shadow-orange-500/20 transition-all hover:shadow-lg hover:shadow-orange-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" %>
                      <% else %>
                        <%= f.submit "SALVAR", class:"middle none center mr-4 rounded-lg bg-green-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-green-500/20 transition-all hover:shadow-lg hover:shadow-green-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" %>
                      <% end %>
                      <%= link_to "VOLTAR", admin_companies_path(@company), class: "middle none center mr-4 rounded-lg bg-blue-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-blue-500/20 transition-all hover:shadow-lg hover:shadow-blue-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/companies/index.html.erb
<section class="py-8 bg-blueGray-50">
  <div class="container px-4 mx-auto flex justify-center">
    <div class="p-7 pb-16 pt-12 border border-dark-blue rounded-3xl w-11/12">
      <div class="flex flex-wrap px-9 md:mb-0">
        <div class="w-full md:w-1/2">
          <h3 class="text-3xl font-heading font-sourcesans font-medium text-gray-700">
            Empresas
          </h3>
        </div>
        <div class="w-full md:w-1/2 max-w-max md:ml-auto">
          <%= link_to "Cadastrar", new_admin_company_path, class: "middle none center mr-4 rounded-lg bg-blue-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-blue-500/20 transition-all hover:shadow-lg hover:shadow-blue-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" %>
        </div>
      </div>
      <div class="overflow-x-auto my-10">
        <div class="inline-block min-w-full overflow-hidden ">
          <table class="table table-zebra w-full my-4">
            <thead>
              <tr>
                <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                  name
                </th>
                <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                  url
                </th>
                <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                  Ações
                </th>
              </tr>
            </thead>

            <tbody>
              <% @companies.each do |company| %>
                <tr>
                  <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 text-left text-blueGray-700">
                    <%= company.name %>
                  </td>
                  <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 text-left text-blueGray-700">
                    <%= company.url %>
                  </td>
                  <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
                      <div class="flex gap-4">
                        <%= link_to edit_admin_company_path(company), class: "middle none center rounded-lg bg-yellow-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-yellow-500/20 transition-all hover:shadow-lg hover:shadow-yellow-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" do %>
                          Editar
                        <% end %> 
                        <%= link_to admin_company_path(company), class:"middle none center rounded-lg bg-green-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-green-500/20 transition-all hover:shadow-lg hover:shadow-green-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" do %>
                          Visualizar
                        <% end %>
                        <%= button_to admin_company_path(company), method: :delete, form: { data: { turbo_confirm: "Você tem certeza?"}}, class:"middle none center rounded-lg bg-red-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-red-500/20 transition-all hover:shadow-lg hover:shadow-red-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" do %>
                          Excluir
                        <% end %>
                      </div>
                    </td>  
              <% end %>
            </tbody>
          </table>
          <%== pagy_nav(@pagy) %>
        </div>
      </div>
    </div>
  </div>
</section>