config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  devise_for :users, controllers: { registrations: "registrations" }
  
  namespace :admin do
    resources :dashboards, only: [:index]
    resources :users
    resources :companies 
    resources :positions, only: [:index]
    
    root to: "dashboards#index"
  end
  
  
  resources :companies, only: [:new, :edit, :create, :update]
  resources :positions do 
    resources :applicants, only: [:index]
    put :update_applicants_status, on: :member
  end

  resources :applicants, only: [:new, :create]
    resources :applied_vacancies, only: [:index]

  root "home#index"
  get "/vaga/:slug", action: :public_position, controller: :positions, as: :public_position
  # dashboard para a empresa
  get "/dashboard", action: :dashboard, controller: :companies, as: :company_dashboard
end

app/views/shared/_flashes.html.erb
<% if flash.any? %>
  <% flash.each do |type, message| %>
    <div class="fixed inset-x-0 top-20 flex items-end justify-right px-4 py-6 sm:p-6 justify-end z-30 pointer-events-none">
      <div data-controller="alert" class="max-w-sm w-full shadow-lg rounded px-4 py-3 rounded relative border-l-4 text-white pointer-events-auto alert <%= tailwind_classes_for(type) %>" data-alert-dismiss-after-value=3000 >
        <div class="p-2">
          <div class="flex items-start">
            <div class="ml-2 flex-1 pt-0.5">
              <p class="text-sm leading-5 font-medium">
              <%= message %>
              </p>
            </div>
            <div class="ml-4 flex-shrink-0 flex">
              <button data-action="alert#close" class="inline-flex text-white focus:outline-none focus:text-gray-300 transition ease-in-out duration-150">
                <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"/>
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>


  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<div data-controller="nav">
  <div class="antialiased bg-gray-200 dark-mode:bg-gray-900">
    <div class="w-full text-gray-700 bg-dark dark-mode:text-gray-200 dark-mode:bg-gray-800">
      <div class="flex flex-col max-w-screen-xl px-4 mx-auto md:items-center md:justify-between md:flex-row md:px-6 lg:px-8 z-50">
        <div class="flex flex-row items-center justify-between p-4">
          <%= link_to root_path, class: "text-lg font-semibold tracking-widest text-gray-900 uppercase rounded-lg dark-mode:text-white focus:outline-none focus:shadow-outline" do %>
            Jobsforvets
          <% end %>
        </div>
        <nav class="flex-col flex-grow hidden pb-4 md:pb-0 md:flex md:justify-end md:flex-row">
          <% unless user_signed_in? %>
            <%= link_to "Login/Cadastro", new_user_session_path, class: "px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
          <% end %>
          <% if user_signed_in? && (current_user.role == "admin" || current_user.role == "company") %>
            <%= link_to "Minha empresa", dynamic_url_company, class: "px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text:white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
            <%= link_to "Publicar vaga", new_position_path, class: "px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text:white dark-mode:hover:text:white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
            <%= link_to "Minhas Vagas", positions_path, class: "px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text:white dark-mode:hover:text:white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
          <% end %>
          <% if user_signed_in? && current_user.role == "company" && current_user.company.positions.any? %>
            <%= link_to "Dashboard", company_dashboard_path, class: "px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text:white dark-mode:hover:text:white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
          <% end %>
          <% if user_signed_in? && current_user.role == "candidate" %>
            <%= link_to "Minhas Vagas", applied_vacancies_path, class: "px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text:white dark-mode:hover:text:white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" %>
          <% end %>
          <% if user_signed_in? %>
            <!-- Settings Dropdown Here -->
            <div class="relative">
              <button type="button" class="inline-flex w-full justify-center gap-x-1.5 rounded-md bg-gray-200 px-3 py-2 text-sm font-semibold dark-mode:bg-transparent dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text:white dark-mode:hover:text:white dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline" id="button-menu" aria-haspopup="true">
                Settings
                <svg id="arrow-icon" class="-mr-1 h-5 w-5 text-gray-400 rotate-up" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd" d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z" clip-rule="evenodd" />
                </svg>
              </button>
              <div id="menu-dropdown" class="hidden absolute right-0 z-10 mt-2 w-56 origin-top-right rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" tabindex="-1">
                <div class="py-1" role="none">
                  <!-- Dropdown menu items -->
                  <a href="#" class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1" id="menu-item-0">Perfil</a>
                  <%= button_to destroy_user_session_path, method: :delete, class: "text-gray-700 block w-full px-4 py-2 text-left text-sm cursor-pointer", role: "menuitem", tabindex: "-1", id: "menu-item-3" do %>
                    Sair
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </nav>
      </div>
    </div>
  </div>
</div>

app/views/shared/_social_network.html.erb
<%= link_to image_tag('social-network/linkedin.svg', class: 'h-8'), "https://www.linkedin.com/sharing/share-offsite/?url=#{url_position(position)}", target: '_blank' %>
<%= link_to image_tag('social-network/whatsapp.svg', class: 'h-8'), "https://wa.me/?text=#{text_position(position)}", target: '_blank' %>
<%= link_to image_tag('social-network/twitter.svg', class: 'h-8'), "https://twitter.com/intent/tweet?text=#{text_position(position)}", target: '_blank' %>
<div data-controller="clipboard">
  <%= link_to image_tag('social-network/copy.svg', class: 'h-8 share-copy-item'), data: { 'clipboard-text': url_position(position) } %>
</div>