config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  devise_for :users, controllers: { registrations: "registrations" }
  
  namespace :admin do
    resources :dashboards, only: [:index]
    resources :users
    resources :companies 
    resources :positions, only: [:index]
    
    root to: "dashboards#index"
  end
  
  
  resources :companies, only: [:new, :edit, :create, :update]
  resources :positions do 
    resources :applicants, only: [:index]
    put :update_applicants_status, on: :member
  end

  resources :applicants, only: [:new, :create]
    resources :applied_vacancies, only: [:index]

  root "home#index"
  get "/vaga/:slug", action: :public_position, controller: :positions, as: :public_position
  # dashboard para a empresa
  get "/dashboard", action: :dashboard, controller: :companies, as: :company_dashboard
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :company
  has_many :applicants

  enum :role, {
    admin: 0,
    company: 1,
    candidate: 2
  }

  validates :role, presence: true

  after_create :welcome_email

  private

  def welcome_email
    UserMailer.welcome(self).deliver_later
  end

  def self.human_enum_name(enum_name, enum_value)
    I18n.t("activerecord.enums.#{model_name.i18n_key}.#{enum_name}.#{enum_value}")
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "role", "updated_at"]
  end
end

app/controllers/admin/users_controller.rb
module Admin
    class UsersController < BaseController
      before_action :set_user, only: [:edit, :update, :destroy, :show]
  
      def index
        @q = User.ransack(params[:q])
        @users = @q.result(distinct: true).order(:email)
        @pagy, @users = pagy(@users)
      end
  
      def show
        render :form
      end
  
      def new
        @user = User.new
        render :form
      end
  
      def create
        @user = User.new(user_params)
        if @user.save
          flash[:success] = "Usuário criado com sucesso!"
          redirect_to action: :index
        else
          render :form, status: :unprocessable_entity
        end
      end
  
      def edit
        render :form
      end
  
      def update
        if @user.update(user_params)
          flash[:notice] = "Usuário atualizado com sucesso!"
          redirect_to action: :index
        else
          render :form, status: :unprocessable_entity
        end
      end
  
      def destroy
        @user.destroy
        redirect_to action: :index
      end
  
      private
  
      def set_user
        @user = User.find(params[:id])
      end
  
      def user_params
        if params[:user][:password].blank?
           params[:user].delete(:password)
           params[:user].delete(:password_confirmation)
        end
  
        params.require(:user).permit(
          :email,
          :password,
          :password_confirmation
        )
      end
    end
  end
  

app/views/admin/users/form.html.erb
<section class="py-8 bg-[#f5f5f5] h-full">
  <div class="container px-10 mx-auto flex justify-center">
    <div class="pb-16 pt-12 border border-dark-blue rounded-3xl w-10/12">
      <p class="text-3xl font-heading font-sourcesans font-medium pl-16">
        <% if action_name == 'show' %>
          <p class="pl-16 text-3xl font-heading font-sourcesans font-medium"> Visualizar usuário </p>
        <% elsif action_name == 'edit' %>
          <p class="pl-16 text-3xl font-heading font-sourcesans font-medium"> Editar usuário </p>
        <% else %>
          <p class="pl-16 text-3xl font-heading font-sourcesans font-medium"> Cadastrar usuário </p>
        <% end %>
      </p>
        <div class="flex flex-wrap px-9 mb-8 md:mb-0 justify-center">
          <div class="mt-5 md:col-span-2 md:mt-0" data-controller="visibility">
            <%= simple_form_for [:admin, @user], defaults: { disabled: action_name == "show" } do |f| %>
              <%= f.error_notification %>
              <div class="overflow-hidden">
                <div class="px-4 py-5 sm:p-6">
                  <div class="grid grid-cols-6 gap-6">
                    <div class="col-span-6 sm:col-span-3">
                      <%= f.input :email,
                              placeholder: "E-mail",
                              class: "block shadow appearance-none border border-gray-300 rounded w-full py-2 px-3 bg-white focus:outline-none focus:ring-0 focus:border-blue-500 text-gray-400 leading-6 transition-colors duration-200 ease-in-out string optional"
                          %>
                    </div>
                    
                    <div class="col-span-6 sm:col-span-3">
                      <%= f.input :role,
                              as: :select,
                              collection: User.roles.keys.map { |role| [User.human_enum_name(:role, role), role] },
                              include_blank: false,
                              selected: @user.role,
                              class: "w-100 shadow appearance-none border border-gray-300 rounded w-full py-2 px-3 bg-white focus:outline-none focus:ring-0 focus:border-blue-500 text-gray-400 leading-6 transition-colors duration-200 ease-in-out string optional"
                          %>
                    </div>

                    <div class="col-span-6 sm:col-span-3">
                      <div class="relative">
                        <%= f.input :password,
                                placeholder: "Senha",
                                class: "shadow appearance-none border border-gray-300 rounded-md w-full py-2 px-3 bg-white focus:outline-none focus:ring-0 focus:border-blue-500 text-gray-400 leading-6 transition-colors duration-200 ease-in-out string optional"
                            %>
                        <div class="absolute -bottom-8 right-0 top-0 pr-3 flex items-center">
                          <svg id="toggle_password_visibility" class="h-5 w-5 text-gray-400 cursor-pointer" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path id="eye_icon_open" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
                            <path id="eye_icon_closed" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.816 6.816a8 8 0 00-11.632 10.368l1.977-1.977a4 4 0 015.658-5.658l1.977-1.977zM4.805 5.085A8 8 0 0017.232 17.8l1.977-1.977a10 10 0 01-14.392-13.888l1.978-1.978z"></path>
                          </svg>
                        </div>
                      </div>
                    </div>

                    <div class="col-span-6 sm:col-span-3">
                      <div class="relative">
                        <%= f.input :password_confirmation,
                                placeholder: "Confirmação de senha",
                                class: "shadow appearance-none border border-gray-300 rounded-md w-full py-2 px-3 bg-white focus:outline-none focus:ring-0 focus:border-blue-500 text-gray-400 leading-6 transition-colors duration-200 ease-in-out string optional"
                        %>
                        <div class="absolute -bottom-8 right-0 top-0 pr-3 flex items-center">
                          <svg id="toggle_confirmation_visibility" class="h-5 w-5 text-gray-400 cursor-pointer" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path id="eye_icon_open" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
                            <path id="eye_icon_closed" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.816 6.816a8 8 0 00-11.632 10.368l1.977-1.977a4 4 0 015.658-5.658l1.977-1.977zM4.805 5.085A8 8 0 0017.232 17.8l1.977-1.977a10 10 0 01-14.392-13.888l1.978-1.978z"></path>
                          </svg>
                        </div>
                      </div>
                    </div>

                      <% if action_name == 'show' %>
                        <%= link_to "EDITAR", edit_admin_user_path(@user), class: "middle none center rounded-lg bg-orange-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-orange-500/20 transition-all hover:shadow-lg hover:shadow-orange-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" %>
                      <% else %>
                        <%= f.submit "SALVAR", class:"middle none center mr-4 rounded-lg bg-green-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-green-500/20 transition-all hover:shadow-lg hover:shadow-green-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" %>
                      <% end %>
                      <%= link_to "VOLTAR", admin_users_path(@user), class: "middle none center mr-4 rounded-lg bg-blue-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-blue-500/20 transition-all hover:shadow-lg hover:shadow-blue-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/users/index.html.erb
<section class="py-8 bg-blueGray-50">
  <div class="container px-4 mx-auto flex justify-center">
    <div class="p-7 pb-16 pt-12 border border-dark-blue rounded-3xl w-11/12">
      <div class="flex flex-wrap px-9 md:mb-0">
        <div class="w-full md:w-1/2">
          <h3 class="text-3xl font-heading font-sourcesans font-medium text-gray-700">
           Usuários
          </h3>
        </div>
        <div class="w-full md:w-1/2 max-w-max md:ml-auto">
          <%= link_to "Cadastrar", new_admin_user_path, class: "middle none center mr-4 rounded-lg bg-blue-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-blue-500/20 transition-all hover:shadow-lg hover:shadow-blue-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" %>
        </div>
      </div>
      <div class="overflow-x-auto my-10">
        <div class="inline-block min-w-full overflow-hidden ">
          <table class="table table-zebra w-full my-4">
            <thead>
              <tr>
                <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                  email
                </th>
                <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                  Ações
                </th>
              </tr>
            </thead>

            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 text-left text-blueGray-700">
                    <%= user.email %>
                  </td>
                  <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
                      <div class="flex gap-4">
                        <%= link_to edit_admin_user_path(user), class: "middle none center rounded-lg bg-yellow-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-yellow-500/20 transition-all hover:shadow-lg hover:shadow-yellow-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" do %>
                          Editar
                        <% end %> 
                        <%= link_to admin_user_path(user), class:"middle none center rounded-lg bg-green-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-green-500/20 transition-all hover:shadow-lg hover:shadow-green-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" do %>
                          Visualizar
                        <% end %>
                        <%= button_to admin_user_path(user), method: :delete, form: { data: { turbo_confirm: "Você tem certeza?"}}, class:"middle none center rounded-lg bg-red-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-red-500/20 transition-all hover:shadow-lg hover:shadow-red-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" do %>
                          Excluir
                        <% end %>
                      </div>
                    </td>  
              <% end %>
            </tbody>
          </table>
          <%== pagy_nav(@pagy) %>
        </div>
      </div>
    </div>
  </div>
</section>